import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { describe, expect, it } from "vitest";

/**
 * Part of #197 — the SHARED PDF TEXT LAYER (api/_lib/pdf-text.js); the
 * drawings page-understanding foundation is NOT this.
 *
 * Deterministic golden TEXT-LAYER test: real unpdf (no model anywhere near
 * this file) against the committed fixtures generated by
 * scripts/generate-pdf-fixtures.js. Asserts the marquee obligations land on
 * their CORRECT pages, the no-text fixture is honestly not-meaningful, and
 * garbage bytes are an honest error — never a silent empty success.
 */

const requireFromHere = createRequire(import.meta.url);
const { extractPdfText, isMeaningfulText, MEANINGFUL_TEXT_MIN_CHARS } = requireFromHere(
  "../../../api/_lib/pdf-text.js"
);

const FIXTURES = new URL("./__fixtures__/", import.meta.url);
const sowPdf = readFileSync(new URL("contract-sow-sample.pdf", FIXTURES));
const noTextPdf = readFileSync(new URL("no-text-scanned.pdf", FIXTURES));

type PageText = { page: number; text: string };
type ExtractOk = { ok: true; pages: PageText[]; totalChars: number };
type ExtractErr = { ok: false; reason: string; message: string };

describe("extractPdfText — synthetic SOW fixture (golden per-page text)", () => {
  it("returns the marquee obligations on their correct 1-based pages", async () => {
    const result = (await extractPdfText(sowPdf)) as ExtractOk;
    expect(result.ok).toBe(true);
    expect(result.pages).toHaveLength(3);
    expect(result.pages.map((p) => p.page)).toEqual([1, 2, 3]);
    expect(result.totalChars).toBeGreaterThan(MEANINGFUL_TEXT_MIN_CHARS);
    expect(isMeaningfulText(result)).toBe(true);

    const [p1, p2, p3] = result.pages.map((p) => p.text);

    // Page 1 — site access & conduct (4 distinct obligations)
    expect(p1).toContain("AMPC site induction is mandatory");
    expect(p1).toContain("SWMS must be uploaded to Sign-on-Site before commencement");
    expect(p1).toContain("six-day working week");
    expect(p1).toContain("Out-of-hours works are by arrangement only");

    // Page 2 — commercial & programme (4 distinct obligations)
    expect(p2).toContain("Progress claims are to be submitted via Payapps");
    expect(p2).toContain("Variations must be approved in writing before work proceeds");
    expect(p2).toContain("Day-labour dockets are to be signed daily");
    expect(p2).toContain("2-week lookahead");
    expect(p2).toContain("4-week programme");

    // Page 3 — quality & closeout (3 distinct obligations)
    expect(p3).toContain("Fire-proofing penetration certificates are required");
    expect(p3).toContain("Structural engineer sign-off is required for core holes");
    expect(p3).toContain("CAD as-builts are required if CADs are not supplied");

    // ...and each phrase is ONLY on its own page (page attribution is real).
    expect(p1).not.toContain("Payapps");
    expect(p2).not.toContain("core holes");
    expect(p3).not.toContain("Sign-on-Site");
  });
});

describe("extractPdfText — honest failure modes", () => {
  it("a no-text (scanned/image-only stand-in) PDF parses but is NOT meaningful", async () => {
    const result = (await extractPdfText(noTextPdf)) as ExtractOk;
    // Parsing succeeds — the honesty gate is isMeaningfulText, so the caller
    // can name the real problem (no text layer / needs OCR, #197).
    expect(result.ok).toBe(true);
    expect(result.totalChars).toBeLessThan(MEANINGFUL_TEXT_MIN_CHARS);
    expect(isMeaningfulText(result)).toBe(false);
  });

  it("garbage bytes are an honest { ok: false } — never a silent empty success", async () => {
    const result = (await extractPdfText(
      Buffer.from("definitely not a portable document format file")
    )) as ExtractErr;
    expect(result.ok).toBe(false);
    expect(result.reason).toBe("not_a_pdf");
    expect(result.message).toBeTruthy();
    expect(isMeaningfulText(result)).toBe(false);
  });

  it("an empty buffer and a non-buffer are honest errors too", async () => {
    expect(((await extractPdfText(Buffer.alloc(0))) as ExtractErr).ok).toBe(false);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- deliberate bad input
    expect(((await extractPdfText("nope" as any)) as ExtractErr).ok).toBe(false);
  });
});
